---
- name: AWS Webserver Compute Configuration
  hosts: webservers
  become: true

  vars:
    user: ec2-user

  tasks:
    - name: Install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Install git
      ansible.builtin.yum:
        name: git
        state: present

    - name: Enable and start httpd
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Enable SSH in firewall
      ansible.posix.firewalld:
        zone: public
        service: ssh
        permanent: true
        state: enabled
      notify: reload firewall

    - name: Enable http in firewall
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled
      notify: Reload firewall

  handlers:
    - name: Reload firewall
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
