---
- name: AWS Webserver Infrastructure
  hosts: localhost
  vars:
    vpc_name: "webserver-vpc"
    project_name: "ansible"
    region: "eu-west-1"
    cidr: "10.0.0.0/16"
    cidr_public_a: "10.0.1.0/24"
    cidr_public_b: "10.0.4.0/24"
    zone1: "a"
    zone2: "b"

  tasks:
  - name: Get ec2 facts
    ec2_instance_info:
      region: "{{ region }}"
      filters:
        "tag:Ansible": webserver
    register: ec2

  - name: Debug
    debug:
      msg: "{{ ec2['instances'].instance_id }}"

#  - name: remove VPC
#    ec2_vpc_net:
#      name: "{{ vpc_name }}"
#     cidr_block: "{{ cidr }}"
#     region: "{{ region }}"
#      state: absent

