---
- name: AWS Webserver Infrastructure
  hosts: localhost
  vars:
    vpc_name: "webserver-vpc"
    project_name: "ansible"
    region: "eu-west-1"
    cidr: "10.0.0.0/16"
    cidr_public_a: "10.0.1.0/24"
    cidr_public_b: "10.0.4.0/24"
    zone1: "a"
    zone2: "b"

  tasks:
  - name: Get ec2 facts
    ec2_instance_info:
      region: "{{ region }}"
      filters:
        "tag:Ansible": webserver
    register: ec2

  - name: Debug
    debug:
      msg: "{{ item }}"
    loop:
      - "{{ ec2['instances'][0].instance_id }}"
      - "{{ ec2['instances'][1].instance_id }}"

  - name: Terminate ec2 instances
    ec2:
      state: 'absent'
      region: "{{ region }}"
      instance_ids: '{{ item }}'
    loop:
      - "{{ ec2['instances'][0].instance_id }}"
      - "{{ ec2['instances'][1].instance_id }}"

  - name: Remove ELB
    ec2_elb_lb:
      name: "webserverelb"
      state: absent
      wait: yes

  - name: Create ELB Target Group
    elb_target_group:
      name: webservers
      region: "{{ region }}"
      state: absent
      wait_timeout: 200

  - name: Get VPC info
    ec2_vpc_net_info:
      region: "{{ region }}"
      filters:
         "tag:Name": "{{ vpc_name }}"
    register: vpc


#  - name: remove VPC
#    ec2_vpc_net:
#      name: "{{ vpc_name }}"
#     cidr_block: "{{ cidr }}"
#     region: "{{ region }}"
#      state: absent

