---
- name: Azure Webserver Infrastructure
  hosts: localhost
  vars:
    resourcegroup: "webserver"
    resourcegroupdns: "dnszones"
    location: "northeurope"

  tasks:
  - name: Delete Resource Group and Content
    azure_rm_resourcegroup:
      name: "{{ resourcegroup }}"
      location: "{{ location }}"
      force_delete_nonempty: yes
      state: absen

  - name: Remove A record for Loadbalancer
    azure_rm_dnsrecordset:
      resource_group: "{{ resourcegroupdns }}"
      relative_name: "{{ hostname }}"
      zone_name: "{{ domain }}"
      record_type: A
      state: absent
