---
- name: Azure Webserver Compute Website
  hosts: tag_ansible_webserver
  become: yes
  user: jesbe
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    gitrepo: https://github.com/jesperberth/tomato-monkey.git
  tasks:
  - name: Download Website from Github
    git:
      repo: "{{ gitrepo }}"
      dest: "/var/www/html"