---
- name: Azure Webserver Compute Website
  hosts: Ansible_webserver
  become: yes
  user: jesbe
  ansible_become_pass: "{{ vmpassword }}"

  tasks:
  - name: Download Website from Github
    git:
      repo: "{{ gitrepo }}"
      dest: "/var/www/html"