---
- name: Azure Webserver Infrastructure
  hosts: localhost
  vars:
    resourcegroup: "webserver"
    resourcegroupdns: "DNSzones"
    location: "northeurope"

  tasks:
  - name: Remove A record for Loadbalancer
    azure_rm_dnsrecordset:
      resource_group: "{{ resourcegroupdns }}"
      relative_name: "{{ hostname }}"
      zone_name: "{{ domain }}"
      record_type: A
      state: absent
