---
- name: OCI Webserver Infrastructure
  hosts: localhost
  vars:
    #compartmentid: "ocid1.compartment.oc1..aaaaaaaapajmuwmqujw2ztssdciccvmjtcyjnaj2ftl62rsohhydoq7qlxza"
    vcn_cidr_block: "10.0.0.0/16"
    vcn_name: "WebsiteNetwork"
    vcn_dns_label: "website"
    subnet_dns_label: "webserver"
    webserver_subnet_name: "webserver"
    webserver_subnet_cidr: "10.0.0.0/24"
    imagename: "oci_image_with_key"
    #hostname: tomat
  
  tasks:
  - name: Get webserver1 facts
    oci_instance_facts:
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ hostname }}-webserver1"
      #lifecycle_state: "RUNNING"
    register: instance_webserver1

  - name: Get webserver2 facts
    oci_instance_facts:
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ hostname }}-webserver2"
      #lifecycle_state: "RUNNING"
    register: instance_webserver2

  - name: Terminate Webserver1
    oci_instance:
       id: "{{ instance_webserver1.instances[0].id }}"
       state: "absent"

  - name: Terminate Webserver2
    oci_instance:
       id: "{{ instance_webserver2.instances[0].id }}"
       state: "absent"

  - name: Load Balancer Facts
    oci_load_balancer_facts:
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ hostname }}-website_lb"
    ignore_errors: yes
    register: lb
  
  - name: Set Fact lb_ip fact
    set_fact:
      lb_public_ip: "{{ item.ip_addresses }}"
    loop: "{{ lb.load_balancers }}"
    ignore_errors: yes

  - name: Set Fact loadbalancer_ip fact
    set_fact:
      loadbalancer_public_ip: "{{ item.ip_address }}"
    loop: "{{ lb_public_ip }}"
    ignore_errors: yes

  - name: Remove zone record for loadbalancer
    oci_zone_records:
      name: "{{ tld }}"
      patch_items: [{
                      domain: "{{ hostname }}.{{ tld }}",
                      is_protected: false,
                      rdata: "{{ loadbalancer_public_ip }}",
                      rtype: "A",
                      ttl: 3600,
                      operation: "REMOVE"
                      }]
    ignore_errors: yes

  - name: Delete Load Balancer
    oci_load_balancer:
      load_balancer_id: "{{ lb.load_balancers[0].id }}"
      state: absent
    ignore_errors: yes

  - name: Get VCN
    oci_vcn_facts:
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ hostname }}_{{ vcn_name }}"
    register: vcn

  - name: List Route Table
    oci_route_table_facts:
      compartment_id: "{{ compartmentid }}"
      vcn_id: "{{ vcn.vcns[0].id }}"
    register: rt

  - name: Get Webserver subnet
    oci_subnet_facts:
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ webserver_subnet_name }}"
      vcn_id: "{{ vcn.vcns[0].id }}"
    register: subnet

  - name: Get Internet Gateway
    oci_internet_gateway_facts:
      compartment_id: "{{ compartmentid }}"
      vcn_id: "{{ vcn.vcns[0].id }}"
    register: inetgw

  - name: Create a Route Table in VCN
    oci_route_table:
      rt_id: "{{ default_route_table_id }}"
      display_name: "webserver default route table"
      route_rules:
          - destination: "0.0.0.0/0"
            destination_type: "CIDR_BLOCK"
            network_entity_id: "{{ rt.route_tables[0].id }}"
      state: absent

  - name : Delete Internet Gateway
    oci_internet_gateway:
      id: "{{ inetgw.internet_gateways[0].id }}"
      state: absent
    ignore_errors: yes

  - name: debug
    debug:
      msg: "{{ inetgw }}"

  - name: Delete subnet
    oci_subnet:
      subnet_id: "{{ subnet.subnets[0].id }}"
      state: absent
    ignore_errors: yes

  - name: Delete vcn
    oci_vcn:
      vcn_id: "{{ vcn.vcns[0].id }}"
      state: absent
    ignore_errors: yes

