---
- name: Vmware
  hosts: localhost
  vars:

  tasks:
- name: Gather disk info from virtual machine using name
  vmware_guest_disk_info:
    datacenter: Datacenter
    name: dc01.redhat.local
  delegate_to: localhost
  register: disk_info