---
- name: Vmware
  hosts: localhost
  vars:

  tasks:
  - name: Look up the VM called test_vm1 in the inventory
    vmware.vmware_rest.vcenter_vm_info:
      filter_names:
      - dc01.redhat.local
    register: search_result